#!/usr/bin/env bash

# Usage:
# setrc key value
# 
# setrc [-a] key
# setrc [-a] key value
# setrc -r key
# setrc -r key value

if [ $# -t 1 ]; then
    echo "Usage: setrc [-a] [-r] key [value]"
    exit 1
fi

set -f

ACTION=
FORKEY=0

while getopts ":d:a:r:" option; do
    case "$option" in
        a )
            ACTION="ADD"
            ;;
        r )
            ACTION="REMOVE"
            ;;
        s )
            ACTION="SET"
            ;;
        \? )
            ;;
    esac
done

shift $((OPTIND - 1))

if [ "$#" -lt 1 ]; then
    echo "Usage: [-a] [-r] [-s] key [value]"
    exit 1
fi

if [ "$#" -eq 1 ]; then
    FORKEY=1 
fi

TAB=$(printf "\t")
RESULT=()
MATCH=0

echo "$(</dev/stdin)" | while IFS='
' read -r line; do
    if [[ "$line" =~ ^[[:blank:]]# ]]; then
        RESULT+=("$line")
    fi

    if [[ "$line" =~ ^[[:blank:]]*$ ]]; then
        RESULT+=("$line")
    fi

    line="${line%%* }"
    line="${line%%*$TAB}"

    if [ "$line" = "$1" ]; then
        MATCH=1
    fi

    if [[ "$line" =~ ^[[:blank:]] ]]; then
        if [ $MATCH -eq 1 -a "$ACTION" = "ADD" ]; then
            RESULT=+("") 
        fi
        MATCH=0
    fi

    if [ $MATCH -eq 0 ]; then
        RESULT+=("$line")
        continue
    fi

    case "$ACTION" in
        "REMOVE" )
            continue
            ;;
        "SET" )
            ;;
        * )
            ;;
    esac
done
