#!/usr/bin/env bash

# Usage:
# setrc [-a] [-r] key value
# 
# setrc [-a] key
# setrc [-a] key value
# setrc -r key
# setrc -r key value

set -f
CWD=$(dirname "$0")

ACTION=ADD

while getopts ":s :a :r" option; do
    case "$option" in
        a )
            ACTION="ADD"
            ;;
        r )
            ACTION="REMOVE"
            ;;
        s )
            ACTION="SET"
            ;;
        \? )
            "Unexcepted option -$option"
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

if [ "$#" -lt 1 ]; then
    echo "Usage: [-a] [-r] [-s] key [value]"
    exit 1
fi

K="$1"
V=
NV=

if [ "$#" -eq 1 ]; then
    case "$ACTION" in
        ADD )
            ACTION="ADD_KEY"
            ;;
        REMOVE )
            ACTION="REMOVE_KEY"
            ;;
        SET )
            ACTION="ADD_KEY"
            ;;
        * )
            ;;
    esac
elif [ "$#" -eq 2 ]; then
    V="$2"
    case "$ACTION" in
        ADD )
            ACTION="ADD_VALUE"
            ;;
        REMOVE )
            ACTION="REMOVE_VALUE"
            ;;
        SET )
            ACTION="SET_KEY"
            ;;
        * )
            ;;
    esac
elif [ "$#" -eq 3 ]; then
    V="$2"
    NV="$3"
    case "$ACTION" in
        ADD )
            echo "Usage: setrc [-a] key"
            echo "       setrc [-a] key value"
            exit 1
            ;;
        REMOVE )
            echo "Usage: setrc -r key"
            echo "       setrc -r key value"
            exit 1
            ;;
        SET )
            ACTION="SET_VALUE"
            ;;
        * )
            ;;
    esac
fi

# replace all leading blank characters to for spaces.
fecho() {
    echo "$1" | sed -E 's/^[\t ]+/    /'
}

INPUT="$(</dev/stdin)"

echo "$INPUT" | $CWD/getrc "$K" > /dev/null 2>&1
X=$?

# if the key not exists in the input content
if [ "$X" = 1 ]; then
    case "$ACTION" in
        # to remove a non-existence key
        REMOVE_* )
           ;;
        # do nothing while setting new value to a non-existence key
        SET_* )
            ;;
        ADD_* )
            INPUT+=$'\n'"$K"
            if [ "$ACTION" = ADD_VALUE ]; then
                INPUT+=$'\n'"    $V"
            fi
            ;;
    esac
    fecho "$INPUT"
    exit
fi

# should not do anything while adding an existence key
if [ "$ACTION" = ADD_KEY ]; then
    fecho "$INPUT"
    exit
fi

TAB=$(printf "\t")
HAS_VALUE=0
MATCH=0

while IFS=$'\n' read -r line; do
    # skip comment lines
    if [[ "$line" =~ ^[[:blank:]]*# ]]; then 
        echo "$line"
        continue
    fi

    # remove blank lines
    if [[ "$line" =~ ^[[:blank:]]*$ ]]; then continue; fi

    line="${line%%* }"
    line="${line%%*$TAB}"

    if [ "$line" = "$K" ]; then
        MATCH=1
        if [ "$ACTION" = SET_KEY ]; then
            fecho "$V"
            continue
        fi
        if [ "$ACTION" = "REMOVE_KEY" ]; then continue; fi
        fecho "$line"
        continue
    fi

    if [[ ! "$line" =~ ^[[:blank:]] ]]; then
        if [ $MATCH -eq 1 -a $HAS_VALUE -eq 0 -a "$ACTION" = "ADD_VALUE" ]; then
            HAS_VALUE=1
            fecho " $V"
        fi
        MATCH=0
    fi

    if [ $MATCH -eq 0 ]; then
        fecho "$line"
        continue
    fi

    line="${line##* }"
    line="${line##*$TAB}"

    case "$ACTION" in
        # remove all values for the key
        REMOVE_KEY )
            continue
            ;;
        REMOVE_VALUE )
            if [ "$line" = "$V" ]; then continue; fi
            fecho " $line"
            ;;
        SET_VALUE )
            if [ "$line" = "$V" ]; then
                fecho " $NV"
                continue
            fi
            fecho " $line"
            ;;
        ADD_VALUE )
            if [ "$line" = "$V" ]; then
                HAS_VALUE=1
                continue
            fi
            fecho " $line"
            ;;
        * )
            fecho " $line"
            ;;
    esac
done <<< "$(echo "$INPUT")"

if [ "$ACTION" = ADD_VALUE -a $HAS_VALUE -eq 0 ]; then
    fecho " $V"
fi
